"""
Django settings for taskmanager project.

Generated by 'django-admin startproject' using Django 5.2.5.
"""

import os
from pathlib import Path
import dj_database_url 
from decouple import config


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# -----------------------------
# SECURITY
# -----------------------------
# -----------------------------
# SECURITY
# -----------------------------
SECRET_KEY = config("SECRET_KEY", default="unsafe-local-secret")
DEBUG = config("DEBUG", cast=bool, default=True)

ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
    'dotty-polluted-ungraphically.ngrok-free.dev',
]
CSRF_TRUSTED_ORIGINS = [
    'https://dotty-polluted-ungraphically.ngrok-free.dev',
    'http://127.0.0.1:8000',
]
DOMAIN= "https://dotty-polluted-ungraphically.ngrok-free.dev"


# -----------------------------
# APPLICATIONS
# -----------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'task'
]


# -----------------------------
# MIDDLEWARE
# -----------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # ✅ Added for static files
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# -----------------------------
# TEMPLATES
# -----------------------------
ROOT_URLCONF = 'taskmanager.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],  # ✅ cleaner way
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'taskmanager.wsgi.application'


# -----------------------------
# DATABASE
# -----------------------------
# -----------------------------
# DATABASE
# -----------------------------
DATABASES = {
    'default': dj_database_url.parse(
        config("DATABASE_URL", default="postgresql://postgres:ihsan@250@localhost:5432/taskmanager"),
        conn_max_age=600
    )
}




# -----------------------------
# PASSWORD VALIDATORS
# -----------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# -----------------------------
# INTERNATIONALIZATION
# -----------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# -----------------------------
# STATIC & MEDIA FILES
# -----------------------------
STATIC_URL = '/static/'  # ✅ always start with /

# ✅ Deployment ke liye static setup (collectstatic will copy here)
STATIC_ROOT = BASE_DIR / "staticfiles"

# ✅ Local development ke liye static folder


# ✅ Whitenoise storage (compress + cache busting)
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# ✅ Media (user uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / "media"


# -----------------------------
# AUTH REDIRECTS
# -----------------------------
LOGIN_REDIRECT_URL = "task_list"
LOGOUT_REDIRECT_URL = "login"  


# -----------------------------
# EMAIL CONFIGURATION
# -----------------------------
# -----------------------------
# EMAIL CONFIGURATION
# -----------------------------
EMAIL_BACKEND = config("EMAIL_BACKEND", default="django.core.mail.backends.smtp.EmailBackend")
EMAIL_HOST = config("EMAIL_HOST", default="smtp.gmail.com")
EMAIL_PORT = config("EMAIL_PORT", cast=int, default=587)
EMAIL_USE_TLS = config("EMAIL_USE_TLS", cast=bool, default=True)
EMAIL_HOST_USER = config("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD", default="")
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


# -----------------------------
# DEFAULT PRIMARY KEY
# -----------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'  # ✅ fix: AUTO_FIELD → DEFAULT_AUTO_FIELD
DDEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL", default=EMAIL_HOST_USER)

