# Generated by Django 5.2.6 on 2025-09-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(default='image.png', upload_to='images/'),
        ),
    ]
