# Generated by Django 5.2.6 on 2025-09-12 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_task_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='image',
            field=models.FileField(default='images/image.png', max_length=250, null=True, upload_to='images/'),
        ),
    ]
